dcsaorg/DCSA-BKG

pom.xml
**Note:** Testing mapstruct in BKG, if it servers our required purpose, will move it to DCSA-Core so it can be used in all projects.
=> Mapstruct cofig

src/main/java/org/dcsa/bkg/controller/BKGController.java, src/main/java/org/dcsa/bkg/model/mappers/BookingMapper.java, src/main/java/org/dcsa/bkg/model/mappers/CommodityMapper.java, src/main/java/org/dcsa/bkg/model/mappers/LocationMapper.java, src/main/java/org/dcsa/bkg/model/transferobjects/AbstractBookingTO.java, src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java, src/test/java/org/dcsa/bkg/controller/BKGControllerTest.java, src/test/java/org/dcsa/bkg/controller/BKGSummariesControllerTest.java, src/test/java/org/dcsa/bkg/model/transferobjects/BookingTOTest.java, src/test/java/org/dcsa/bkg/service/BookingServiceImplTest.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-542
=> POST booking req impl shallow

src/test/java/org/dcsa/bkg/controller/BKGControllerTest.java, src/test/java/org/dcsa/bkg/service/impl/BookingServiceImplTest.java
Resolves https://dcsa.atlassian.net/browse/DDT-612
=> DDT-612 limited statusses in documentStatus

src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java, src/test/java/org/dcsa/bkg/service/impl/BookingServiceImplTest.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-544
=> Added implementation for shipment locations in POST Booking

src/main/java/org/dcsa/bkg/controller/BKGConfirmedBookingsController.java, src/main/java/org/dcsa/bkg/controller/BKGController.java, src/test/java/org/dcsa/bkg/controller/BKGConfirmedBookingsControllerTest.java, src/test/java/org/dcsa/bkg/controller/BKGControllerTest.java
=> Ddt 634 corrected base path for cancelation

src/main/java/org/dcsa/bkg/controller/BKGConfirmationSummariesController.java, src/test/java/org/dcsa/bkg/controller/BKGConfirmationSummariesControllerTest.java
=> DDT-643 fixed booking confirmation summaries path to align it with OAS

src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java, src/test/java/org/dcsa/bkg/service/impl/BookingServiceImplTest.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-641
=> Added logic for linking vessel to booking in POST

src/main/resources/application.yaml
=> Added API version property used in API-Version response header

src/main/java/org/dcsa/bkg/controller/BKGController.java, src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java, src/test/java/org/dcsa/bkg/controller/BKGControllerTest.java, src/test/java/org/dcsa/bkg/service/impl/BookingServiceImplTest.java
**Note:** Update of Document Parties and Shipment Location within booking is pending.
=> Added most of the implementation for update booking

src/main/java/org/dcsa/bkg/controller/BKGController.java, src/main/java/org/dcsa/bkg/model/transferobjects/ShipmentSummaryTO.java, src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java, src/test/java/org/dcsa/bkg/controller/BKGControllerTest.java, src/test/java/org/dcsa/bkg/controller/BKGShipmentControllerTest.java, src/test/java/org/dcsa/bkg/controller/BKGShipmentSummariesControllerTest.java, src/test/java/org/dcsa/bkg/service/impl/BookingServiceImplTest.java
=> Ddt 648 add documentstatus carrierbookingrequestreference to shipment summary

src/main/java/org/dcsa/bkg/model/transferobjects/AbstractBookingTO.java, src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java, src/test/java/org/dcsa/bkg/controller/BKGControllerTest.java, src/test/java/org/dcsa/bkg/service/impl/BookingServiceImplTest.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-506
=> Added impl to update document parties and shipment locations.

src/main/java/org/dcsa/bkg/controller/BKGShipmentSummariesController.java, src/main/java/org/dcsa/bkg/model/mappers/ShipmentMapper.java, src/main/java/org/dcsa/bkg/model/transferobjects/ShipmentSummaryTO.java, src/main/java/org/dcsa/bkg/model/transferobjects/ShipmentTO.java, src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java, src/test/java/org/dcsa/bkg/controller/BKGShipmentSummariesControllerTest.java, src/test/java/org/dcsa/bkg/model/transferobjects/ShipmentTOTest.java, src/test/java/org/dcsa/bkg/service/impl/BookingServiceImplTest.java
Resolves: DDT-673 
depends on: https://github.com/dcsaorg/DCSA-BKG/pull/50
=> Ddt 673 added created updated datetime to shipment

src/main/java/org/dcsa/bkg/controller/BKGShipmentSummariesController.java, src/main/java/org/dcsa/bkg/controller/BKGSummariesController.java, src/main/java/org/dcsa/bkg/controller/util/Pagination.java, src/main/java/org/dcsa/bkg/model/mappers/BookingMapper.java, src/main/java/org/dcsa/bkg/model/mappers/BookingSummaryMapper.java, src/main/java/org/dcsa/bkg/model/mappers/ShipmentMapper.java, src/main/java/org/dcsa/bkg/model/transferobjects/AbstractBookingTO.java, src/main/java/org/dcsa/bkg/model/transferobjects/ShipmentSummaryTO.java, src/main/java/org/dcsa/bkg/model/transferobjects/ShipmentTO.java, src/main/java/org/dcsa/bkg/service/BookingService.java, src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java, src/test/java/org/dcsa/bkg/controller/BKGControllerTest.java, src/test/java/org/dcsa/bkg/controller/BKGShipmentSummariesControllerTest.java, src/test/java/org/dcsa/bkg/controller/BKGSummariesControllerTest.java, src/test/java/org/dcsa/bkg/controller/util/PaginationTest.java, src/test/java/org/dcsa/bkg/model/transferobjects/ShipmentTOTest.java, src/test/java/org/dcsa/bkg/service/impl/BookingServiceImplTest.java
proposed solution for pagination. Updated booking to include bookingRequestUpdatedDateTime and bookingRequestCreatedDateTime
Depends on: https://github.com/dcsaorg/DCSA-Event-Core/pull/171 
needs rebuild after https://github.com/dcsaorg/DCSA-Event-Core/pull/171 is merged
=> Pagination

src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java
This PR resolves bugs found in following PR: [DDT-488](https://github.com/dcsaorg/DCSA-API-Validator/pull/114)
=> Ddt-711-fixes bugs found when testing

src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-715
=> Fixes duplicate booking bug on creating shipment event in POST booking.

src/main/java/org/dcsa/bkg/controller/BKGController.java, src/main/java/org/dcsa/bkg/model/transferobjects/BookingCancellationRequestTO.java, src/main/java/org/dcsa/bkg/service/BookingService.java, src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java, src/test/java/org/dcsa/bkg/controller/BKGControllerTest.java, src/test/java/org/dcsa/bkg/service/impl/BookingServiceImplTest.java
=> DDT-713 aligned cancel booking with latest OAS

src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java, src/test/java/org/dcsa/bkg/service/impl/BookingServiceImplTest.java
=> DDT-722 cancellation of booking sends CANC shipmentevent

src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java
=> Use concatMap on bookingSummaries

src/main/java/org/dcsa/bkg/controller/BKGController.java, src/main/java/org/dcsa/bkg/service/BookingService.java, src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java, src/test/java/org/dcsa/bkg/controller/BKGControllerTest.java, src/test/java/org/dcsa/bkg/service/impl/BookingServiceImplTest.java
- updated body response & unit tests
=> DDT-672: PUT response payload

src/main/java/org/dcsa/bkg/model/transferobjects/AbstractBookingTO.java, src/main/java/org/dcsa/bkg/service/impl/BookingServiceImpl.java, src/main/resources/application.yaml, src/test/java/org/dcsa/bkg/service/impl/BookingServiceImplTest.java
Dependent on: https://dcsa.atlassian.net/browse/DDT-758
=> DDT-752: Conditional check for expectedDepartureDate in POST/PUT

.editorconfig, .github/workflows/dev.yml, .github/workflows/master.yml, .gitignore, Dockerfile, pom.xml
This build on https://github.com/dcsaorg/DCSA-BKG/pull/91
=> Ddt 925 java17

src/main/java/org/dcsa/bkg/model/transferobjects/AbstractBookingTO.java, src/main/java/org/dcsa/bkg/service/impl/BKGServiceImpl.java, src/test/java/org/dcsa/bkg/service/impl/BKGServiceImplTest.java
Dependent on: https://github.com/dcsaorg/DCSA-Information-Model/pull/253 and https://github.com/dcsaorg/DCSA-Event-Core/pull/292
=> DDT-991: RequestedEquipmentEquipment

src/main/java/org/dcsa/bkg/model/enums/TransportPlanStage.java, src/main/java/org/dcsa/bkg/service/impl/BookingSummaryServiceImpl.java
Signed-off-by: Niels Thykier <nt@asseco.dk>
=> Simplify some of the code

.github/workflows/dev.yml, pom.xml, src/main/java/org/dcsa/bkg/service/impl/BKGServiceImpl.java, src/test/java/org/dcsa/bkg/service/impl/BKGServiceImplTest.java
=> Ddt 957 implement versioning get booking

pom.xml, src/main/java/org/dcsa/bkg/controller/BKGEventController.java, src/main/java/org/dcsa/bkg/controller/BKGSummariesController.java, src/main/java/org/dcsa/bkg/extendedRequest/ShipmentSummaryExtendedRequest.java, src/main/java/org/dcsa/bkg/model/transferobjects/AbstractBookingTO.java
Signed-off-by: Niels Thykier <nt@asseco.dk>
Depends on https://github.com/dcsaorg/DCSA-Event-Core/pull/312
=> DDT-958: Respect validUntil in summaries endpoints

src/main/java/org/dcsa/bkg/service/impl/BKGServiceImpl.java, src/test/java/org/dcsa/bkg/service/impl/BKGServiceImplTest.java
Signed-off-by: Niels Thykier <nt@asseco.dk>
=> DDT-1037: Split TC ID and TC Reference

src/main/java/org/dcsa/bkg/service/impl/BKGServiceImpl.java, src/test/java/org/dcsa/bkg/service/impl/BKGServiceImplTest.java
depends on: https://github.com/dcsaorg/DCSA-Event-Core/pull/326
moved helper methods of shipment_events into mappers in event_core and moved the check methods to Booking entity.
=> moved shipmentEvent helper methods to ShipmentEventMapper

README.md
fix for: https://github.com/dcsaorg/DCSA-BKG/issues/122
=> Fix spring-boot:run argument
